name = "vazy"
main = "src/index.ts"
compatibility_date = "2026-04-16"

[vars]
APP_ORIGIN = "https://www.wazymenu.fr"
ADMIN_TOKEN = "yaya"

[env.dev]

[env.dev.vars]
APP_ORIGIN = "http://localhost:5173"
ADMIN_TOKEN = "yaya"

[[r2_buckets]]
binding = "PRIVATE_MENUS"
bucket_name = "vazy-private-menus"

[[kv_namespaces]]
binding = "RESTAURANTS" 
id = "e345b0fad31c40b684337dda71d4a941"

[[d1_databases]]
binding = "DB"
database_name = "vazy"
database_id = "d5d1e7b3-fe33-460c-af83-d18b7e2d31d0"

# Optional: for local dev you can use `wrangler kv:namespace create` and set the id.
